/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Root_calculator.Controller.Controller;
import Root_calculator.Factory.TypeMethod;
import Root_calculator.Graficadora.Function;
import Root_calculator.Graficadora.G;
import Root_calculator.Method.MethodResult;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EL_DEO
 */
public class Principal1 extends javax.swing.JFrame {

    Controller x = Controller.getInstance();
    TypeMethod type ;
    
    G grafica = new G("Graficadora", "Eje X", "Eje Y");
    public Principal1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRBisepccion = new javax.swing.JRadioButton();
        jRRegulaFalsi = new javax.swing.JRadioButton();
        jRNewton = new javax.swing.JRadioButton();
        jRSecante = new javax.swing.JRadioButton();
        Funcion = new javax.swing.JTextField();
        jPanel3 = grafica.DibujarGrafica();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        Tolerancia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        A = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        D = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        B1 = new javax.swing.JTextField();
        A1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MN-2023");
        setMaximumSize(new java.awt.Dimension(650, 800));
        setMinimumSize(new java.awt.Dimension(650, 800));
        setPreferredSize(new java.awt.Dimension(650, 800));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(650, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Métodos para determinar raices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRBisepccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBisepccion.setForeground(new java.awt.Color(255, 255, 255));
        jRBisepccion.setText("Bisección ");
        jRBisepccion.setOpaque(false);
        jRBisepccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBisepccionActionPerformed(evt);
            }
        });
        jPanel6.add(jRBisepccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, 144, -1));

        jRRegulaFalsi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRRegulaFalsi.setForeground(new java.awt.Color(255, 255, 255));
        jRRegulaFalsi.setText("Regula Falsi");
        jRRegulaFalsi.setOpaque(false);
        jRRegulaFalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRegulaFalsiActionPerformed(evt);
            }
        });
        jPanel6.add(jRRegulaFalsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, -1, -1));

        jRNewton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRNewton.setForeground(new java.awt.Color(255, 255, 255));
        jRNewton.setText("Newton");
        jRNewton.setOpaque(false);
        jRNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNewtonActionPerformed(evt);
            }
        });
        jPanel6.add(jRNewton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 29, -1, -1));

        jRSecante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRSecante.setForeground(new java.awt.Color(255, 255, 255));
        jRSecante.setText("Secante");
        jRSecante.setOpaque(false);
        jRSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSecanteActionPerformed(evt);
            }
        });
        jPanel6.add(jRSecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 150));

        Funcion.setBackground(new java.awt.Color(0, 0, 0));
        Funcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Funcion.setForeground(new java.awt.Color(255, 255, 255));
        Funcion.setText("e^(x*2)+x");
        Funcion.setBorder(null);
        Funcion.setOpaque(false);
        Funcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionActionPerformed(evt);
            }
        });
        jPanel2.add(Funcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 190, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 370, 350));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(0, 204, 0));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(0, 204, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Iteracion", "Valor de X", "Error "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 600, 270));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 10));

        Tolerancia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tolerancia.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Tolerancia.setText("0.002");
        jPanel2.add(Tolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Funcíon");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tolerancia");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 30));

        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel2.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 40, 25));
        jPanel2.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 40, 25));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Mandalore Expanded", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 90, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Mandalore Expanded", 0, 14)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Mandalore Expanded", 0, 18)); // NOI18N
        jButton3.setText("Graficar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 30));

        D.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        D.setText("0.1");
        jPanel2.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Intervalo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 30));

        B1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        B1.setText("5");
        B1.setMaximumSize(new java.awt.Dimension(6, 20));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel2.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 40, 30));

        A1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        A1.setText("-5");
        A1.setMaximumSize(new java.awt.Dimension(6, 20));
        jPanel2.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionActionPerformed

    private void jRBisepccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBisepccionActionPerformed
        type = TypeMethod.Mbiseccion;
        jLabel4.setText("Intervalos");
        B.setVisible(true);  
    }//GEN-LAST:event_jRBisepccionActionPerformed

    private void jRRegulaFalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRegulaFalsiActionPerformed
        type = TypeMethod.MRegula_falsi;
        jLabel4.setText("Intervalos");
        B.setVisible(true); 
    }//GEN-LAST:event_jRRegulaFalsiActionPerformed

    private void jRNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNewtonActionPerformed
  if(jRNewton.isSelected()){
         type = TypeMethod.MNewton;
        jLabel4.setText("Aproximación inicial");
        B.setVisible(false);    
        }

    }//GEN-LAST:event_jRNewtonActionPerformed

    private void jRSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSecanteActionPerformed
        type = TypeMethod.MSecante;
        jLabel4.setText("Intervalos");
        B.setVisible(true); 
    }//GEN-LAST:event_jRSecanteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        
        String tempfuncion = Funcion.getText();
        double temptolerancia = Double.valueOf(Tolerancia.getText());
        double a = Double.valueOf(A.getText());
        double b = Double.valueOf(B.getText());
        
        x.setFunction(tempfuncion);
        x.setTolerance(temptolerancia);
        x.setIntervalos(a, b);
        x.setTypeMethod(type);
        
        try{
        x.Resolver();

        ArrayList<MethodResult> solution = x.getSolution();
        DefaultTableModel model = new DefaultTableModel();
        String row[] = {"Iteracion","Valor de x" ,"Error"};
        
        model.setColumnIdentifiers(row);
              
        for (int i = 0; i < solution.size(); i++) {
         
            row[0] = String.valueOf(i+1);
            row[1] = solution.get(i).getXvalue();
            row[2] = solution.get(i).getEm();
            model.addRow(row);
        }
        
        
        jTable1.setModel(model);
        jTable1.setVisible(true);
        jScrollPane1.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "Resultado calculado con éxito");

        }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, "Se ha encontrado un error");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        String def = Funcion.getText();
        double x0 = Double.parseDouble(A1.getText());
        double xn = Double.parseDouble(B1.getText());
        double d = Double.parseDouble(D.getText());
        
        Function f = new Function(def);
        double [] x =f.rango(x0, xn, d);
        try{
        double [] y =f.eval(x);
        grafica.crearGrafica(def, x, y);
        grafica.DibujarGrafica();

        }
        catch(Exception e){
            
        }
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField A1;
    private javax.swing.JTextField B;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField D;
    private javax.swing.JTextField Funcion;
    private javax.swing.JTextField Tolerancia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRBisepccion;
    private javax.swing.JRadioButton jRNewton;
    private javax.swing.JRadioButton jRRegulaFalsi;
    private javax.swing.JRadioButton jRSecante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
