/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Functionalities_Methods.NumericOptimitation.SeccionAurea;
import Functionalities_Methods.NumericOptimitation.SolutionSeccionDorada;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EL_DEO
 */
public class jPanelNumeric_Oprimitation extends javax.swing.JPanel {

    private char c;
    public jPanelNumeric_Oprimitation() {
        initComponents();
        this.c = '>';
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFuncion = new javax.swing.JTextField();
        TexIntA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextIntB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextTolerancia = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButtonMaximizar = new javax.swing.JRadioButton();
        jRadioButtonMinimizar = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFuncion.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        add(TextFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 200, -1));

        TexIntA.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TexIntA.setText("-10");
        add(TexIntA, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 45, 78, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Función");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TextIntB.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TextIntB.setText("10");
        add(TextIntB, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 45, 76, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Intervalo para calcular ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 16, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Tolerancia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        TextTolerancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextTolerancia.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextTolerancia.setText("0.002");
        add(TextTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Mandalore Expanded", 0, 18)); // NOI18N
        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 106, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "I", "A", "B", "X1", "X2", "F(x1)", "F(x2)", "L"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 630, 350));

        jRadioButtonMaximizar.setText("Maximizar");
        jRadioButtonMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaximizarActionPerformed(evt);
            }
        });
        add(jRadioButtonMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 111, -1, -1));

        jRadioButtonMinimizar.setText("Minimizar");
        jRadioButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMinimizarActionPerformed(evt);
            }
        });
        add(jRadioButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 111, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String def = TextFuncion.getText();
        double A = Double.valueOf(TexIntA.getText());
        double B = Double.valueOf(TextIntB.getText());
        double Tolerancia = Double.valueOf(TextTolerancia.getText());

        SeccionAurea metodo = new SeccionAurea();
        metodo.loadDate(def, A, B, Tolerancia);
        ArrayList<SolutionSeccionDorada> temp = metodo.optimitation(c);

        DefaultTableModel model = new DefaultTableModel();
        String row[] = {"I", "A","B", "X1", "X2", "F(x1)", "F(x2)", "L"};

        model.setColumnIdentifiers(row);

        for (int i = 0; i < temp.size(); i++) {

            //                        //Definir cantidad de decimales
            //                        String Xn = formato.format(solution.get(i).getXvalue());
            //                        String Em = formato.format(solution.get(i).getEm());
            
            
            row[0] = String.valueOf(i);
            row[1] = String.valueOf(temp.get(i).solution()[0]);
            row[2] = String.valueOf(temp.get(i).solution()[1]);
            row[3] = String.valueOf(temp.get(i).solution()[2]);
            row[4] = String.valueOf(temp.get(i).solution()[3]);
            row[5] = String.valueOf(temp.get(i).solution()[4]);
            row[6] = String.valueOf(temp.get(i).solution()[5]);
            row[7] = String.valueOf(temp.get(i).solution()[6]);
            

            model.addRow(row);
        }
        jTable1.setModel(model);
        jTable1.setVisible(true);
        //jScrollPane1.setVisible(true);
        //JOptionPane.showMessageDialog(this, SMS.Mensage_2());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButtonMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaximizarActionPerformed
        if(jRadioButtonMaximizar.isSelected()){
            c = '>';
        }
        else{
            c ='<';
        }
    }//GEN-LAST:event_jRadioButtonMaximizarActionPerformed

    private void jRadioButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMinimizarActionPerformed
        if(jRadioButtonMinimizar.isSelected()){
            c = '<';
        }
        else{
            c = '>';
        }
    }//GEN-LAST:event_jRadioButtonMinimizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TexIntA;
    private javax.swing.JTextField TextFuncion;
    private javax.swing.JTextField TextIntB;
    private javax.swing.JTextField TextTolerancia;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonMaximizar;
    private javax.swing.JRadioButton jRadioButtonMinimizar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
