/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import Functionalities_Methods.Ecuaction_Systems.Gauss_Seidel;
import Functionalities_Methods.Ecuaction_Systems.Jacobi;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EL_DEO
 */
public class jPanel_Ecuation_Systems extends javax.swing.JPanel {

    
    
    private DecimalFormat formato;
    private String decimales;
    
    public jPanel_Ecuation_Systems() {
        initComponents();
        
        this.CentrarTabla(TablaValores);
        this.CentrarTabla(Soluciones);
        this.CentrarTabla(Aproximaciones);
        this.TablaValores.setShowHorizontalLines(true);
        this.TablaValores.setShowVerticalLines(true);
        this.Soluciones.setShowHorizontalLines(true);
        this.Aproximaciones.setShowHorizontalLines(true);
        this.decimales = "#.####";
        this.formato  = new DecimalFormat(decimales);
        jJacobi.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerGrado = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaValores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pizarra = new javax.swing.JTextArea();
        jJacobi = new javax.swing.JRadioButton();
        jSidel = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Soluciones = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Aproximaciones = new javax.swing.JTable();
        Tolerancia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerDecimales = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 510));
        setMinimumSize(new java.awt.Dimension(800, 510));
        setPreferredSize(new java.awt.Dimension(800, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setText("Numero de incognitas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, 25));

        jSpinnerGrado.setModel(new javax.swing.SpinnerNumberModel(2, 1, 10, 1));
        jSpinnerGrado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerGradoStateChanged(evt);
            }
        });
        add(jSpinnerGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 11, 50, 30));

        TablaValores.setBackground(new java.awt.Color(0, 0, 0));
        TablaValores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TablaValores.setForeground(new java.awt.Color(255, 255, 255));
        TablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "X0", "X1"
            }
        ));
        TablaValores.setGridColor(new java.awt.Color(0, 204, 0));
        jScrollPane1.setViewportView(TablaValores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 421, 129));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        Pizarra.setBackground(new java.awt.Color(0, 0, 0));
        Pizarra.setColumns(20);
        Pizarra.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        Pizarra.setForeground(new java.awt.Color(0, 255, 0));
        Pizarra.setRows(5);
        jScrollPane4.setViewportView(Pizarra);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 790, 230));

        jJacobi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jJacobi);
        jJacobi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jJacobi.setText("Jacobi");
        add(jJacobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 13, -1, -1));

        jSidel.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jSidel);
        jSidel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jSidel.setText("Gauss-Sidel");
        add(jSidel, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 13, -1, -1));

        Soluciones.setBackground(new java.awt.Color(0, 0, 0));
        Soluciones.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Soluciones.setForeground(new java.awt.Color(255, 255, 255));
        Soluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Soluciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Soluciones.setGridColor(new java.awt.Color(0, 204, 0));
        Soluciones.setRowSelectionAllowed(false);
        Soluciones.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Soluciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(Soluciones);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 92, 117, 129));

        Aproximaciones.setBackground(new java.awt.Color(0, 0, 0));
        Aproximaciones.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Aproximaciones.setForeground(new java.awt.Color(255, 255, 255));
        Aproximaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0"},
                {"0"}
            },
            new String [] {
                "Aproximación inicial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Aproximaciones.setGridColor(new java.awt.Color(0, 204, 0));
        Aproximaciones.setRowSelectionAllowed(false);
        Aproximaciones.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Aproximaciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(Aproximaciones);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 92, 134, 129));
        add(Tolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 170, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Tolerancia");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jSpinnerDecimales.setModel(new javax.swing.SpinnerNumberModel(4, 1, 15, 1));
        jSpinnerDecimales.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerDecimalesStateChanged(evt);
            }
        });
        add(jSpinnerDecimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerGradoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerGradoStateChanged

        DefaultTableModel modelo = (DefaultTableModel) TablaValores.getModel();
        DefaultTableModel modeloSolt = (DefaultTableModel) Soluciones.getModel();
        DefaultTableModel modelAproX = (DefaultTableModel) Aproximaciones.getModel();
        int ecuaciones = modelo.getColumnCount();
        int total = (int) jSpinnerGrado.getValue();

        if(ecuaciones < total){
            for(int i = ecuaciones ; i < total ; i++){
                modelo.addColumn("X"+i);
                modelo.addRow(new Vector());
                modeloSolt.addRow(new Vector());
                String temp [] = {"0"}; 
                modelAproX.addRow(temp);
            }
        }
        else if(ecuaciones > total){
            modelo.setColumnCount(total);
            modelo.setRowCount(total);
            modeloSolt.setRowCount(total);
            modelAproX.setRowCount(total);
            
        }

        this.CentrarTabla(TablaValores);
        this.CentrarTabla(Soluciones);
        this.CentrarTabla(Aproximaciones);
    }//GEN-LAST:event_jSpinnerGradoStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int size = (int) jSpinnerGrado.getModel().getValue();
        
        double value_x[][] = new double[size][size];
        double value_y[] = new double[size];
        double inicial[] = new double[size];
        
        for(int i = 0 ; i < size ; i ++){
            for(int j = 0 ; j < size ; j++){
                value_x[j][i] =  Double.valueOf((String)TablaValores.getValueAt(j, i));
            }
            value_y[i] =  Double.valueOf((String)Soluciones.getValueAt(i, 0));
            inicial[i] = Double.valueOf((String)Aproximaciones.getValueAt(i, 0));
        }
        
        
        if(jSidel.isSelected()){
        Gauss_Seidel temp = new Gauss_Seidel();
        temp.GaussSeidel(value_x, value_y, Double.valueOf(Tolerancia.getText()),inicial);
        Pizarra.setText(temp.getsteps(formato));
        }
        else{
            Jacobi temp = new Jacobi();
            temp.jacobi(value_x, value_y, Double.valueOf(Tolerancia.getText()), inicial);
            Pizarra.setText(temp.getsteps(formato));
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinnerDecimalesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerDecimalesStateChanged

        
        int value = (int) jSpinnerDecimales.getValue();
        if (value > decimales.length()) {
            decimales = "#.";
            for (int i = 0; i < value ; i++) {
                decimales = decimales + "#";
            }
        } else if (value < decimales.length()) {

            decimales = "#.";
            for (int i = 0; i < value ; i++) {
                decimales = decimales + "#";
            }
        }
        this.formato = new DecimalFormat(decimales);
    }//GEN-LAST:event_jSpinnerDecimalesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Aproximaciones;
    private javax.swing.JTextArea Pizarra;
    private javax.swing.JTable Soluciones;
    private javax.swing.JTable TablaValores;
    private javax.swing.JTextField Tolerancia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jJacobi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton jSidel;
    private javax.swing.JSpinner jSpinnerDecimales;
    private javax.swing.JSpinner jSpinnerGrado;
    // End of variables declaration//GEN-END:variables



private void CentrarTabla(JTable tabla) {

        DefaultTableCellRenderer centrar = new DefaultTableCellRenderer();
        centrar.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(centrar);
            DefaultTableCellRenderer r = (DefaultTableCellRenderer) tabla.getTableHeader().getDefaultRenderer();
            r.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }









}
