/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Panels;

import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EL_DEO
 */
public class jPanelSistemasDeEcuaciones extends javax.swing.JPanel {

    /**
     * Creates new form jPanelEcuacionesLineales
     */
    public jPanelSistemasDeEcuaciones() {
        initComponents();
        
        this.CentrarTabla(TablaValores);
        this.CentrarTabla(Soluciones);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerGrado = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        Soluciones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaValores = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setText("Numero de incognitas");

        jSpinnerGrado.setModel(new javax.swing.SpinnerNumberModel(2, 1, 5, 1));
        jSpinnerGrado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerGradoStateChanged(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ecuaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 14))); // NOI18N

        Soluciones.setBackground(new java.awt.Color(0, 0, 0));
        Soluciones.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        Soluciones.setForeground(new java.awt.Color(0, 255, 0));
        Soluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1"},
                {"2.72"}
            },
            new String [] {
                "Soluciones"
            }
        ));
        Soluciones.setGridColor(new java.awt.Color(0, 255, 204));
        Soluciones.setRowHeight(24);
        Soluciones.setRowSelectionAllowed(false);
        Soluciones.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Soluciones);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ecuaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 14))); // NOI18N

        TablaValores.setBackground(new java.awt.Color(0, 0, 0));
        TablaValores.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        TablaValores.setForeground(new java.awt.Color(0, 255, 0));
        TablaValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2"},
                {"2.72", "7.39"}
            },
            new String [] {
                "X0", "X1"
            }
        ));
        TablaValores.setGridColor(new java.awt.Color(0, 255, 204));
        TablaValores.setRowHeight(24);
        TablaValores.setRowSelectionAllowed(false);
        TablaValores.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(TablaValores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jSpinnerGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerGradoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerGradoStateChanged

        DefaultTableModel modelo = (DefaultTableModel) TablaValores.getModel();
        DefaultTableModel modeloSolt = (DefaultTableModel) Soluciones.getModel();
        
        int ecuaciones = modelo.getColumnCount();
        int total = (int) jSpinnerGrado.getValue();

        if(ecuaciones < total){
            for(int i = ecuaciones ; i < total ; i++){
                modelo.addColumn("X"+i);
                modelo.addRow(new Vector(total));
                modeloSolt.addRow(new Vector(1));
            }
        }
        else if(ecuaciones > total){
            modelo.setColumnCount(total);
            modelo.setRowCount(total);
            modeloSolt.setRowCount(total);
            
            
        }

        this.CentrarTabla(TablaValores);
        this.CentrarTabla(Soluciones);
    }//GEN-LAST:event_jSpinnerGradoStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Soluciones;
    private javax.swing.JTable TablaValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerGrado;
    // End of variables declaration//GEN-END:variables



private void CentrarTabla(JTable tabla) {

        DefaultTableCellRenderer centrar = new DefaultTableCellRenderer();
        centrar.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(centrar);
            DefaultTableCellRenderer r = (DefaultTableCellRenderer) tabla.getTableHeader().getDefaultRenderer();
            r.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }









}
